### ISSUE TITLE
Support Ruby 3.2

### ISSUE THREAD

**Issue by grobie** [stripe-ruby-mock/stripe-ruby-mock#855]
# Problem

Ruby 3.2 removed the long deprecated `File.exists?` method in favor of `File.exist?`

```console
$ ruby -v
ruby 3.2.0 (2022-12-25 revision a528908271) [x86_64-linux]
$ bundle exec rspec
Finished in 3 minutes 39.2 seconds (files took 43.23 seconds to load)
5818 examples, 109 failures, 1 pending
```

**Comment by grobie** [comment]
This has been fixed already in https://github.com/stripe-ruby-mock/stripe-ruby-mock/commit/c8f388b3690dab29fbd9fd6b7ab13b0c683f47fa, but is not part of the latest release 3.1.0.rc3 from 2021-07-14.

Cutting a new release will resolve this issue @TastyPi. Thank you for your work!

**Comment by coreyhaines** [comment]
Thanks for the work on this; it can be a lot to maintain a gem that grows popular.

Checking in on this to see if a new version is going to be cut that will have this fix?

**Comment by TastyPi** [comment]
I don't have permissions to create releases on RubyGems, you'll have to ask @gilbert @grobie or @csalvato.

FWIW we've been using git in our `Gemfile` instead of rubygems due to the lack of regular updates, e.g. `gem "stripe-ruby-mock", github: "stripe-ruby-mock/stripe-ruby-mock", ref: "<some commit hash>", require: "stripe_mock"`. It's not ideal, but until RubyGem permissions are given to someone who actually has the time/motivation to keep this project maintained it's the best option.

**Comment by coreyhaines** [comment]
Thanks @TastyPi .
I put in a monkeypatch for this method to update it. :) That also worked.

I can definitely understand the time/motivation for folks working on OS stuff.

**Comment by tomasc** [comment]
For the time being I solve this using [file_exists](https://github.com/Largo/file_exists)

**Comment by nroose** [comment]
Any chance we can have a release so that this out sooner? Or a patch to v3.1.0? Maybe as a non-"rc" 3.1.0?

**Comment by alexmamonchik** [comment]
> Any chance we can have a release so that this out sooner? Or a patch to v3.1.0? Maybe as a non-"rc" 3.1.0?

done.

**Comment by alexmamonchik** [comment]
in #897 we'll support 3.2
